/* Generated by Pyrex 0.7.2 on Mon May 05 15:12:33 2003 */

#include "Python.h"
#include "structmember.h"
#include "string.h"


static PyObject *__Pyx_UnpackItem(PyObject *, int); /*proto*/
static int __Pyx_EndUnpack(PyObject *, int); /*proto*/
static int __Pyx_PrintItem(PyObject *); /*proto*/
static int __Pyx_PrintNewline(void); /*proto*/
static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static void __Pyx_ReRaise(void); /*proto*/
static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/
static PyObject *__Pyx_GetExcValue(void); /*proto*/
static PyObject *__Pyx_GetName(PyObject *dict, char *name); /*proto*/
static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed, char *name); /*proto*/
static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/
static int __Pyx_GetStarArgs(PyObject **args, PyObject **kwds, char *kwd_list[], int nargs, PyObject **args2, PyObject **kwds2); /*proto*/
static void __Pyx_WriteUnraisable(char *name); /*proto*/
static void __Pyx_AddTraceback(char *funcname); /*proto*/
static PyTypeObject *__Pyx_ImportType(char *module_name, char *class_name, long size);  /*proto*/

static PyObject *__pyx_m;
static PyObject *__pyx_b;
static int __pyx_lineno;
static char *__pyx_filename;
static char __pyx_mdoc[] = "Gap-based Mutable Character Buffer";
static char *__pyx_f1 = "C:\\cygwin\\home\\pje\\PEAK\\src/peak/util/buffer_gap.pyx";

staticforward PyTypeObject __pyx_type_Buffer;

struct __pyx_obj_Buffer {
  PyObject_HEAD
  int gap;
  int gapsize;
  int length;
  int size;
  int alloc;
  char (*buffer);
};

static PyObject *__pyx_k2;
static int __pyx_k3;
static PyObject *__pyx_k5;
static int __pyx_k6;
static int (__pyx_f__checkIndex(int ,int ,int )); /*proto*/
static int (__pyx_f__fixupIndex(struct __pyx_obj_Buffer *,int )); /*proto*/
static void (__pyx_f__setGap(struct __pyx_obj_Buffer *,int )); /*proto*/
static int (__pyx_f__setGapSize(struct __pyx_obj_Buffer *,int )); /*proto*/


static int __pyx_f__checkIndex(int __pyx_v_p,int __pyx_v_len,int __pyx_v_hi) {
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":21 */
  __pyx_1 = (__pyx_v_p < 0);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":22 */
    __pyx_v_p = (__pyx_v_p + __pyx_v_len);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":24 */
  __pyx_1 = (__pyx_v_p < 0);
  if (!__pyx_1) {
    __pyx_1 = (__pyx_v_p >= __pyx_v_hi);
  }
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":25 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "IndexError"); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 25; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_p); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 25; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_3, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f1; __pyx_lineno = 25; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":27 */
  __pyx_r = __pyx_v_p;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("buffer_gap._checkIndex");
  __pyx_r = -1;
  __pyx_L0:;
  return __pyx_r;
}


static int __pyx_f__fixupIndex(struct __pyx_obj_Buffer *__pyx_v_self,int __pyx_v_p) {
  int __pyx_r;
  int __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":32 */
  __pyx_1 = __pyx_f__checkIndex(__pyx_v_p,__pyx_v_self->length,__pyx_v_self->length); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 32; goto __pyx_L1;}
  __pyx_v_p = __pyx_1;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":34 */
  __pyx_1 = (__pyx_v_p >= __pyx_v_self->gap);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":35 */
    __pyx_v_p = (__pyx_v_p + __pyx_v_self->gapsize);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":37 */
  __pyx_r = __pyx_v_p;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("buffer_gap._fixupIndex");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static void __pyx_f__setGap(struct __pyx_obj_Buffer *__pyx_v_self,int __pyx_v_pos) {
  char (*__pyx_v_buf);
  int __pyx_v_move;
  int __pyx_v_after;
  int __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":44 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":45 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":47 */
  __pyx_1 = (__pyx_v_pos != __pyx_v_self->gap);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":49 */
    __pyx_v_after = (__pyx_v_self->gap + __pyx_v_self->gapsize);

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":51 */
    __pyx_1 = (__pyx_v_pos < __pyx_v_self->gap);
    if (__pyx_1) {

      /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":52 */
      __pyx_v_move = (__pyx_v_self->gap - __pyx_v_pos);

      /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":53 */
      memmove((&(__pyx_v_self->buffer[(__pyx_v_after - __pyx_v_move)])),(&(__pyx_v_self->buffer[__pyx_v_pos])),__pyx_v_move);
      goto __pyx_L3;
    }
    /*else*/ {

      /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":56 */
      __pyx_v_move = (__pyx_v_pos - __pyx_v_self->gap);

      /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":57 */
      memmove((&(__pyx_v_self->buffer[__pyx_v_self->gap])),(&(__pyx_v_self->buffer[__pyx_v_after])),__pyx_v_move);
    }
    __pyx_L3:;

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":59 */
    __pyx_v_self->gap = __pyx_v_pos;
    goto __pyx_L2;
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("buffer_gap._setGap");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}


static int __pyx_f__setGapSize(struct __pyx_obj_Buffer *__pyx_v_self,int __pyx_v_size) {
  int __pyx_v_count;
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  void (*__pyx_6);
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":64 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":66 */
  __pyx_1 = (__pyx_v_size > __pyx_v_self->gapsize);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":68 */
    __pyx_f__setGap(__pyx_v_self,__pyx_v_self->length);

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":70 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "min"); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 70; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_size); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 70; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_self->alloc); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 70; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f1; __pyx_lineno = 70; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 70; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __pyx_1 = PyInt_AsLong(__pyx_3); if (PyErr_Occurred()) {__pyx_filename = __pyx_f1; __pyx_lineno = 70; goto __pyx_L1;}
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    __pyx_v_count = __pyx_1;

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":72 */
    __pyx_6 = PyMem_Realloc(__pyx_v_self->buffer,(__pyx_v_self->size + __pyx_v_count)); if (__pyx_6 == 0) {__pyx_filename = __pyx_f1; __pyx_lineno = 72; goto __pyx_L1;}
    __pyx_v_self->buffer = ((char (*))__pyx_6);

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":74 */
    __pyx_v_self->gapsize = (__pyx_v_self->gapsize + __pyx_v_count);

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":75 */
    __pyx_v_self->size = (__pyx_v_self->size + __pyx_v_count);
    goto __pyx_L2;
  }
  __pyx_L2:;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("buffer_gap._setGapSize");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static int __pyx_f_6Buffer___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_6Buffer___new__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_initializer = 0;
  int __pyx_v_alloc;
  int __pyx_r;
  static char *__pyx_argnames[] = {"initializer","alloc",0};
  __pyx_v_initializer = __pyx_k2;
  __pyx_v_alloc = __pyx_k3;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|Oi", __pyx_argnames, &__pyx_v_initializer, &__pyx_v_alloc)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_initializer);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":89 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->size = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":90 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->gap = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":91 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->length = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":92 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->gapsize = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":93 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":94 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->alloc = __pyx_v_alloc;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("buffer_gap.Buffer.__new__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_initializer);
  return __pyx_r;
}


static void __pyx_f_6Buffer___dealloc__(PyObject *__pyx_v_self); /*proto*/
static void __pyx_f_6Buffer___dealloc__(PyObject *__pyx_v_self) {
  int __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":97 */
  __pyx_1 = (((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer != 0);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":98 */
    PyMem_Free(((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer);
    goto __pyx_L2;
  }
  __pyx_L2:;

  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_WriteUnraisable("buffer_gap.Buffer.__dealloc__");
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
}


static int __pyx_f_6Buffer___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static int __pyx_f_6Buffer___init__(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_initializer = 0;
  int __pyx_v_alloc;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"initializer","alloc",0};
  __pyx_v_initializer = __pyx_k5;
  __pyx_v_alloc = __pyx_k6;
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "|Oi", __pyx_argnames, &__pyx_v_initializer, &__pyx_v_alloc)) return -1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_initializer);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":101 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "__setslice__"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(0); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_Buffer *)__pyx_v_self)->length); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 101; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 101; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  Py_INCREF(__pyx_v_initializer);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_v_initializer);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 101; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("buffer_gap.Buffer.__init__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_initializer);
  return __pyx_r;
}


static PyObject *__pyx_f_6Buffer___str__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_6Buffer___str__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":104 */
  __pyx_1 = PySequence_GetSlice(__pyx_v_self, 0, ((struct __pyx_obj_Buffer *)__pyx_v_self)->length); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 104; goto __pyx_L1;}
  __pyx_r = __pyx_1;
  __pyx_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("buffer_gap.Buffer.__str__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_6Buffer___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_f_6Buffer___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":107 */
  __pyx_1 = __Pyx_GetName(__pyx_b, "repr"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 107; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_b, "str"); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 107; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 107; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_self);
  __pyx_4 = PyObject_CallObject(__pyx_2, __pyx_3); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 107; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 107; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 107; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_r = __pyx_3;
  __pyx_3 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("buffer_gap.Buffer.__repr__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static int __pyx_f_6Buffer___len__(PyObject *__pyx_v_self); /*proto*/
static int __pyx_f_6Buffer___len__(PyObject *__pyx_v_self) {
  int __pyx_r;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":110 */
  __pyx_r = ((struct __pyx_obj_Buffer *)__pyx_v_self)->length;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("buffer_gap.Buffer.__len__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_6Buffer___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_p); /*proto*/
static PyObject *__pyx_f_6Buffer___getitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_p) {
  int __pyx_v_p;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_p = PyInt_AsLong(__pyx_arg_p); if (PyErr_Occurred()) {__pyx_filename = __pyx_f1; __pyx_lineno = 112; goto __pyx_L1;}

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":113 */
  __pyx_1 = __pyx_f__fixupIndex(((struct __pyx_obj_Buffer *)__pyx_v_self),__pyx_v_p); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 113; goto __pyx_L1;}
  __pyx_v_p = __pyx_1;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":114 */
  __pyx_2 = PyInt_FromLong((((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer[__pyx_v_p])); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 114; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("buffer_gap.Buffer.__getitem__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static int __pyx_f_6Buffer___setitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_p, PyObject *__pyx_arg_x); /*proto*/
static int __pyx_f_6Buffer___setitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_p, PyObject *__pyx_arg_x) {
  int __pyx_v_p;
  int __pyx_v_x;
  int __pyx_r;
  int __pyx_1;
  Py_INCREF(__pyx_v_self);
  __pyx_v_p = PyInt_AsLong(__pyx_arg_p); if (PyErr_Occurred()) {__pyx_filename = __pyx_f1; __pyx_lineno = 116; goto __pyx_L1;}
  __pyx_v_x = PyInt_AsLong(__pyx_arg_x); if (PyErr_Occurred()) {__pyx_filename = __pyx_f1; __pyx_lineno = 116; goto __pyx_L1;}

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":117 */
  __pyx_1 = __pyx_f__fixupIndex(((struct __pyx_obj_Buffer *)__pyx_v_self),__pyx_v_p); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 117; goto __pyx_L1;}
  __pyx_v_p = __pyx_1;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":118 */
  (((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer[__pyx_v_p]) = __pyx_v_x;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("buffer_gap.Buffer.__setitem__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static int __pyx_f_6Buffer___delitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_p); /*proto*/
static int __pyx_f_6Buffer___delitem__(PyObject *__pyx_v_self, PyObject *__pyx_arg_p) {
  int __pyx_v_p;
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_self);
  __pyx_v_p = PyInt_AsLong(__pyx_arg_p); if (PyErr_Occurred()) {__pyx_filename = __pyx_f1; __pyx_lineno = 120; goto __pyx_L1;}

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":121 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "__delslice__"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 121; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_v_p); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 121; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong((__pyx_v_p + 1)); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 121; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 121; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 121; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("buffer_gap.Buffer.__delitem__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_6Buffer_insert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6Buffer_insert(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_p;
  int __pyx_v_x;
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  static char *__pyx_argnames[] = {"p","x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "ii", __pyx_argnames, &__pyx_v_p, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":126 */
  __pyx_1 = (__pyx_v_p < 0);
  if (!__pyx_1) {
    __pyx_1 = (__pyx_v_p > ((struct __pyx_obj_Buffer *)__pyx_v_self)->length);
  }
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":127 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "IndexError"); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 127; goto __pyx_L1;}
    __pyx_3 = PyInt_FromLong(__pyx_v_p); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 127; goto __pyx_L1;}
    __Pyx_Raise(__pyx_2, __pyx_3, 0);
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f1; __pyx_lineno = 127; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":129 */
  __pyx_1 = (((struct __pyx_obj_Buffer *)__pyx_v_self)->gapsize == 0);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":130 */
    __pyx_1 = __pyx_f__setGapSize(((struct __pyx_obj_Buffer *)__pyx_v_self),1); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 130; goto __pyx_L1;}
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":132 */
  __pyx_f__setGap(((struct __pyx_obj_Buffer *)__pyx_v_self),__pyx_v_p);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":134 */
  (((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer[__pyx_v_p]) = __pyx_v_x;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":136 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->gapsize = (((struct __pyx_obj_Buffer *)__pyx_v_self)->gapsize - 1);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":137 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->gap = (((struct __pyx_obj_Buffer *)__pyx_v_self)->gap + 1);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":138 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->length = (((struct __pyx_obj_Buffer *)__pyx_v_self)->length + 1);

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("buffer_gap.Buffer.insert");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_6Buffer_append(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6Buffer_append(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  int __pyx_v_x;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"x",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "i", __pyx_argnames, &__pyx_v_x)) return 0;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":142 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "insert"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 142; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_Buffer *)__pyx_v_self)->length); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 142; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(__pyx_v_x); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 142; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(2); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 142; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 142; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("buffer_gap.Buffer.append");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_6Buffer_extend(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static PyObject *__pyx_f_6Buffer_extend(PyObject *__pyx_v_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  PyObject *__pyx_v_aStr = 0;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  static char *__pyx_argnames[] = {"aStr",0};
  if (!PyArg_ParseTupleAndKeywords(__pyx_args, __pyx_kwds, "O", __pyx_argnames, &__pyx_v_aStr)) return 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_aStr);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":146 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "__setslice__"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_Buffer *)__pyx_v_self)->length); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_Buffer *)__pyx_v_self)->length); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 146; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 146; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  Py_INCREF(__pyx_v_aStr);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_v_aStr);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 146; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("buffer_gap.Buffer.extend");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_aStr);
  return __pyx_r;
}


static int __pyx_f_6Buffer___setslice__(PyObject *__pyx_v_self, int __pyx_v_i, int __pyx_v_j, PyObject *__pyx_v_x); /*proto*/
static int __pyx_f_6Buffer___setslice__(PyObject *__pyx_v_self, int __pyx_v_i, int __pyx_v_j, PyObject *__pyx_v_x) {
  int __pyx_v_change;
  int __pyx_v_datalen;
  void (*__pyx_v_data);
  int __pyx_r;
  int __pyx_1;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":167 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":168 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":170 */
  __pyx_1 = __pyx_f__checkIndex(__pyx_v_i,((struct __pyx_obj_Buffer *)__pyx_v_self)->length,(((struct __pyx_obj_Buffer *)__pyx_v_self)->length + 1)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 170; goto __pyx_L1;}
  __pyx_v_i = __pyx_1;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":171 */
  __pyx_1 = __pyx_f__checkIndex(__pyx_v_j,((struct __pyx_obj_Buffer *)__pyx_v_self)->length,(((struct __pyx_obj_Buffer *)__pyx_v_self)->length + 1)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 171; goto __pyx_L1;}
  __pyx_v_j = __pyx_1;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":175 */
  __pyx_1 = PyObject_AsReadBuffer(__pyx_v_x,(&__pyx_v_data),(&__pyx_v_datalen)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 175; goto __pyx_L1;}

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":176 */
  __pyx_v_change = (__pyx_v_datalen - (__pyx_v_j - __pyx_v_i));

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":178 */
  __pyx_1 = (__pyx_v_change > 0);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":179 */
    __pyx_1 = __pyx_f__setGapSize(((struct __pyx_obj_Buffer *)__pyx_v_self),__pyx_v_change); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 179; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":181 */
  __pyx_f__setGap(((struct __pyx_obj_Buffer *)__pyx_v_self),__pyx_v_i);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":183 */
  __pyx_1 = __pyx_v_datalen;
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":184 */
    memmove((&(((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer[__pyx_v_i])),__pyx_v_data,__pyx_v_datalen);
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":186 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->gapsize = (((struct __pyx_obj_Buffer *)__pyx_v_self)->gapsize - __pyx_v_change);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":187 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->gap = (((struct __pyx_obj_Buffer *)__pyx_v_self)->gap + __pyx_v_change);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":188 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->length = (((struct __pyx_obj_Buffer *)__pyx_v_self)->length + __pyx_v_change);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("buffer_gap.Buffer.__setslice__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}

static char (__pyx_k7[]) = "";

static PyObject *__pyx_f_6Buffer___getslice__(PyObject *__pyx_v_self, int __pyx_v_i, int __pyx_v_j); /*proto*/
static PyObject *__pyx_f_6Buffer___getslice__(PyObject *__pyx_v_self, int __pyx_v_i, int __pyx_v_j) {
  PyObject *__pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":193 */
  __pyx_1 = __pyx_f__checkIndex(__pyx_v_i,((struct __pyx_obj_Buffer *)__pyx_v_self)->length,(((struct __pyx_obj_Buffer *)__pyx_v_self)->length + 1)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 193; goto __pyx_L1;}
  __pyx_v_i = __pyx_1;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":194 */
  __pyx_1 = __pyx_f__checkIndex(__pyx_v_j,((struct __pyx_obj_Buffer *)__pyx_v_self)->length,(((struct __pyx_obj_Buffer *)__pyx_v_self)->length + 1)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 194; goto __pyx_L1;}
  __pyx_v_j = __pyx_1;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":196 */
  __pyx_1 = (((struct __pyx_obj_Buffer *)__pyx_v_self)->gap < __pyx_v_j);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":197 */
    __pyx_f__setGap(((struct __pyx_obj_Buffer *)__pyx_v_self),((struct __pyx_obj_Buffer *)__pyx_v_self)->length);
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":199 */
  __pyx_1 = ((__pyx_v_j - __pyx_v_i) > 0);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":200 */
    __pyx_2 = PyString_FromStringAndSize((&(((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer[__pyx_v_i])),(__pyx_v_j - __pyx_v_i)); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 200; goto __pyx_L1;}
    __pyx_r = __pyx_2;
    __pyx_2 = 0;
    goto __pyx_L0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":202 */
  __pyx_2 = PyString_FromString(__pyx_k7); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 202; goto __pyx_L1;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("buffer_gap.Buffer.__getslice__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static int __pyx_f_6Buffer___delslice__(PyObject *__pyx_v_self, int __pyx_v_i, int __pyx_v_j); /*proto*/
static int __pyx_f_6Buffer___delslice__(PyObject *__pyx_v_self, int __pyx_v_i, int __pyx_v_j) {
  int __pyx_v_change;
  int __pyx_r;
  int __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":208 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":210 */
  __pyx_1 = __pyx_f__checkIndex(__pyx_v_i,((struct __pyx_obj_Buffer *)__pyx_v_self)->length,(((struct __pyx_obj_Buffer *)__pyx_v_self)->length + 1)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 210; goto __pyx_L1;}
  __pyx_v_i = __pyx_1;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":211 */
  __pyx_1 = __pyx_f__checkIndex(__pyx_v_j,((struct __pyx_obj_Buffer *)__pyx_v_self)->length,(((struct __pyx_obj_Buffer *)__pyx_v_self)->length + 1)); if (__pyx_1 == -1) {__pyx_filename = __pyx_f1; __pyx_lineno = 211; goto __pyx_L1;}
  __pyx_v_j = __pyx_1;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":213 */
  __pyx_v_change = (__pyx_v_i - __pyx_v_j);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":215 */
  __pyx_f__setGap(((struct __pyx_obj_Buffer *)__pyx_v_self),__pyx_v_i);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":217 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->gapsize = (((struct __pyx_obj_Buffer *)__pyx_v_self)->gapsize - __pyx_v_change);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":218 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->gap = (((struct __pyx_obj_Buffer *)__pyx_v_self)->gap + __pyx_v_change);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":219 */
  ((struct __pyx_obj_Buffer *)__pyx_v_self)->length = (((struct __pyx_obj_Buffer *)__pyx_v_self)->length + __pyx_v_change);

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("buffer_gap.Buffer.__delslice__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static PyObject *__pyx_f_6Buffer___iadd__(PyObject *__pyx_v_self, PyObject *__pyx_v_x); /*proto*/
static PyObject *__pyx_f_6Buffer___iadd__(PyObject *__pyx_v_self, PyObject *__pyx_v_x) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_x);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":223 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_self, "__setslice__"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 223; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(((struct __pyx_obj_Buffer *)__pyx_v_self)->length); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 223; goto __pyx_L1;}
  __pyx_3 = PyInt_FromLong(((struct __pyx_obj_Buffer *)__pyx_v_self)->length); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 223; goto __pyx_L1;}
  __pyx_4 = PyTuple_New(3); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 223; goto __pyx_L1;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  PyTuple_SET_ITEM(__pyx_4, 1, __pyx_3);
  Py_INCREF(__pyx_v_x);
  PyTuple_SET_ITEM(__pyx_4, 2, __pyx_v_x);
  __pyx_2 = 0;
  __pyx_3 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_4); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 223; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_4); __pyx_4 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":224 */
  Py_INCREF(__pyx_v_self);
  __pyx_r = __pyx_v_self;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("buffer_gap.Buffer.__iadd__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_x);
  return __pyx_r;
}


static PyObject *__pyx_f_6Buffer___add__(PyObject *__pyx_v_x, PyObject *__pyx_v_y); /*proto*/
static PyObject *__pyx_f_6Buffer___add__(PyObject *__pyx_v_x, PyObject *__pyx_v_y) {
  int __pyx_v_alloc;
  PyObject *__pyx_v_newBuf;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  Py_INCREF(__pyx_v_x);
  Py_INCREF(__pyx_v_y);
  __pyx_v_newBuf = Py_None; Py_INCREF(__pyx_v_newBuf);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":229 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":231 */
  __pyx_1 = __Pyx_GetName(__pyx_b, "isinstance"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 231; goto __pyx_L1;}
  __pyx_2 = __Pyx_GetName(__pyx_m, "Buffer"); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 231; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 231; goto __pyx_L1;}
  Py_INCREF(__pyx_v_x);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_x);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 231; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_2); if (__pyx_4 < 0) {__pyx_filename = __pyx_f1; __pyx_lineno = 231; goto __pyx_L1;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  if (__pyx_4) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":232 */
    __pyx_v_alloc = ((struct __pyx_obj_Buffer *)__pyx_v_x)->alloc;
    goto __pyx_L2;
  }
  __pyx_1 = __Pyx_GetName(__pyx_b, "isinstance"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 233; goto __pyx_L1;}
  __pyx_3 = __Pyx_GetName(__pyx_m, "Buffer"); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 233; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(2); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 233; goto __pyx_L1;}
  Py_INCREF(__pyx_v_y);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_y);
  PyTuple_SET_ITEM(__pyx_2, 1, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 233; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyObject_IsTrue(__pyx_3); if (__pyx_4 < 0) {__pyx_filename = __pyx_f1; __pyx_lineno = 233; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  if (__pyx_4) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":234 */
    __pyx_v_alloc = ((struct __pyx_obj_Buffer *)__pyx_v_y)->alloc;
    goto __pyx_L2;
  }
  /*else*/ {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":236 */
    __pyx_v_alloc = 512;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":238 */
  __pyx_1 = __Pyx_GetName(__pyx_m, "Buffer"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 238; goto __pyx_L1;}
  __pyx_2 = PyInt_FromLong(__pyx_v_alloc); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 238; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(2); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 238; goto __pyx_L1;}
  Py_INCREF(__pyx_v_x);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_x);
  PyTuple_SET_ITEM(__pyx_3, 1, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 238; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_v_newBuf);
  __pyx_v_newBuf = __pyx_2;
  __pyx_2 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":239 */
  __pyx_1 = PyObject_GetAttrString(__pyx_v_newBuf, "extend"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 239; goto __pyx_L1;}
  __pyx_3 = PyTuple_New(1); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 239; goto __pyx_L1;}
  Py_INCREF(__pyx_v_y);
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_v_y);
  __pyx_2 = PyObject_CallObject(__pyx_1, __pyx_3); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 239; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":240 */
  Py_INCREF(__pyx_v_newBuf);
  __pyx_r = __pyx_v_newBuf;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(__pyx_r);
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("buffer_gap.Buffer.__add__");
  __pyx_r = 0;
  __pyx_L0:;
  Py_DECREF(__pyx_v_newBuf);
  Py_DECREF(__pyx_v_x);
  Py_DECREF(__pyx_v_y);
  return __pyx_r;
}


static int __pyx_f_6Buffer___cmp__(PyObject *__pyx_v_self, PyObject *__pyx_v_ob); /*proto*/
static int __pyx_f_6Buffer___cmp__(PyObject *__pyx_v_self, PyObject *__pyx_v_ob) {
  int __pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  int __pyx_4;
  Py_INCREF(__pyx_v_self);
  Py_INCREF(__pyx_v_ob);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":248 */
  __pyx_1 = __Pyx_GetName(__pyx_b, "str"); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 248; goto __pyx_L1;}
  __pyx_2 = PyTuple_New(1); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 248; goto __pyx_L1;}
  Py_INCREF(__pyx_v_self);
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_v_self);
  __pyx_3 = PyObject_CallObject(__pyx_1, __pyx_2); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 248; goto __pyx_L1;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_4 = PyObject_Compare(__pyx_3,__pyx_v_ob); if (PyErr_Occurred()) {__pyx_filename = __pyx_f1; __pyx_lineno = 248; goto __pyx_L1;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_r = __pyx_4;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("buffer_gap.Buffer.__cmp__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  Py_DECREF(__pyx_v_ob);
  return __pyx_r;
}

static char (__pyx_k8[]) = "Invalid read segment";

static int __pyx_f_6Buffer___getreadbuffer__(PyObject *__pyx_v_self, int __pyx_v_segment, void (*(*__pyx_v_p))); /*proto*/
static int __pyx_f_6Buffer___getreadbuffer__(PyObject *__pyx_v_self, int __pyx_v_segment, void (*(*__pyx_v_p))) {
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":253 */
  __pyx_1 = __pyx_v_segment;
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":254 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "SystemError"); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 254; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k8); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 254; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_segment); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 254; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f1; __pyx_lineno = 254; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 254; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f1; __pyx_lineno = 254; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":256 */
  __pyx_f__setGap(((struct __pyx_obj_Buffer *)__pyx_v_self),((struct __pyx_obj_Buffer *)__pyx_v_self)->length);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":257 */
  (__pyx_v_p[0]) = ((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":258 */
  __pyx_r = ((struct __pyx_obj_Buffer *)__pyx_v_self)->length;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("buffer_gap.Buffer.__getreadbuffer__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k9[]) = "Invalid write segment";

static int __pyx_f_6Buffer___getwritebuffer__(PyObject *__pyx_v_self, int __pyx_v_segment, void (*(*__pyx_v_p))); /*proto*/
static int __pyx_f_6Buffer___getwritebuffer__(PyObject *__pyx_v_self, int __pyx_v_segment, void (*(*__pyx_v_p))) {
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":263 */
  __pyx_1 = __pyx_v_segment;
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":264 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "SystemError"); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 264; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k9); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 264; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_segment); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 264; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f1; __pyx_lineno = 264; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 264; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f1; __pyx_lineno = 264; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":266 */
  __pyx_f__setGap(((struct __pyx_obj_Buffer *)__pyx_v_self),((struct __pyx_obj_Buffer *)__pyx_v_self)->length);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":267 */
  (__pyx_v_p[0]) = ((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":268 */
  __pyx_r = ((struct __pyx_obj_Buffer *)__pyx_v_self)->length;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("buffer_gap.Buffer.__getwritebuffer__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static char (__pyx_k10[]) = "Invalid character segment";

static int __pyx_f_6Buffer___getcharbuffer__(PyObject *__pyx_v_self, int __pyx_v_segment, char (*(*__pyx_v_p))); /*proto*/
static int __pyx_f_6Buffer___getcharbuffer__(PyObject *__pyx_v_self, int __pyx_v_segment, char (*(*__pyx_v_p))) {
  int __pyx_r;
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  PyObject *__pyx_5 = 0;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":273 */
  __pyx_1 = __pyx_v_segment;
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":274 */
    __pyx_2 = __Pyx_GetName(__pyx_b, "SystemError"); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 274; goto __pyx_L1;}
    __pyx_3 = PyString_FromString(__pyx_k10); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 274; goto __pyx_L1;}
    __pyx_4 = PyInt_FromLong(__pyx_v_segment); if (!__pyx_4) {__pyx_filename = __pyx_f1; __pyx_lineno = 274; goto __pyx_L1;}
    __pyx_5 = PyTuple_New(2); if (!__pyx_5) {__pyx_filename = __pyx_f1; __pyx_lineno = 274; goto __pyx_L1;}
    PyTuple_SET_ITEM(__pyx_5, 0, __pyx_3);
    PyTuple_SET_ITEM(__pyx_5, 1, __pyx_4);
    __pyx_3 = 0;
    __pyx_4 = 0;
    __pyx_3 = PyObject_CallObject(__pyx_2, __pyx_5); if (!__pyx_3) {__pyx_filename = __pyx_f1; __pyx_lineno = 274; goto __pyx_L1;}
    Py_DECREF(__pyx_2); __pyx_2 = 0;
    Py_DECREF(__pyx_5); __pyx_5 = 0;
    __Pyx_Raise(__pyx_3, 0, 0);
    Py_DECREF(__pyx_3); __pyx_3 = 0;
    {__pyx_filename = __pyx_f1; __pyx_lineno = 274; goto __pyx_L1;}
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":276 */
  __pyx_f__setGap(((struct __pyx_obj_Buffer *)__pyx_v_self),((struct __pyx_obj_Buffer *)__pyx_v_self)->length);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":277 */
  (__pyx_v_p[0]) = ((struct __pyx_obj_Buffer *)__pyx_v_self)->buffer;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":278 */
  __pyx_r = ((struct __pyx_obj_Buffer *)__pyx_v_self)->length;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  Py_XDECREF(__pyx_5);
  __Pyx_AddTraceback("buffer_gap.Buffer.__getcharbuffer__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}


static int __pyx_f_6Buffer___getsegcount__(PyObject *__pyx_v_self, int (*__pyx_v_p)); /*proto*/
static int __pyx_f_6Buffer___getsegcount__(PyObject *__pyx_v_self, int (*__pyx_v_p)) {
  int __pyx_r;
  int __pyx_1;
  Py_INCREF(__pyx_v_self);

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":283 */
  __pyx_1 = (__pyx_v_p != 0);
  if (__pyx_1) {

    /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":284 */
    (__pyx_v_p[0]) = ((struct __pyx_obj_Buffer *)__pyx_v_self)->length;
    goto __pyx_L2;
  }
  __pyx_L2:;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":286 */
  __pyx_r = 1;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1:;
  __Pyx_AddTraceback("buffer_gap.Buffer.__getsegcount__");
  __pyx_r = -1;
  __pyx_L0:;
  Py_DECREF(__pyx_v_self);
  return __pyx_r;
}

static PyObject *__pyx_tp_new_Buffer(struct _typeobject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  struct __pyx_obj_Buffer *p = (struct __pyx_obj_Buffer *)o;
  if (__pyx_f_6Buffer___new__(o, a, k) < 0) {
    Py_DECREF(o); o = 0;
  }
  return o;
}

static void __pyx_tp_dealloc_Buffer(PyObject *o) {
  struct __pyx_obj_Buffer *p = (struct __pyx_obj_Buffer *)o;
  {
    PyObject *etype, *eval, *etb;
    PyErr_Fetch(&etype, &eval, &etb);
    ++o->ob_refcnt;
    __pyx_f_6Buffer___dealloc__(o);
    if (PyErr_Occurred()) PyErr_WriteUnraisable(o);
    --o->ob_refcnt;
    PyErr_Restore(etype, eval, etb);
  }
  (*o->ob_type->tp_free)(o);
}

static int __pyx_tp_traverse_Buffer(PyObject *o, visitproc v, void *a) {
  int e;
  struct __pyx_obj_Buffer *p = (struct __pyx_obj_Buffer *)o;
  return 0;
}

static int __pyx_tp_clear_Buffer(PyObject *o) {
  struct __pyx_obj_Buffer *p = (struct __pyx_obj_Buffer *)o;
  return 0;
}
static PyObject *__pyx_sq_item_Buffer(PyObject *o, int i) {
  PyObject *x = PyInt_FromLong(i); if(!x) return 0;
  return o->ob_type->tp_as_mapping->mp_subscript(o, x);
}

static int __pyx_mp_ass_subscript_Buffer(PyObject *o, PyObject *i, PyObject *v) {
  if (v) {
    return __pyx_f_6Buffer___setitem__(o, i, v);
  }
  else {
    return __pyx_f_6Buffer___delitem__(o, i);
  }
}

static int __pyx_sq_ass_slice_Buffer(PyObject *o, int i, int j, PyObject *v) {
  if (v) {
    return __pyx_f_6Buffer___setslice__(o, i, j, v);
  }
  else {
    return __pyx_f_6Buffer___delslice__(o, i, j);
  }
}

static struct PyMethodDef __pyx_methods_Buffer[] = {
  {"insert", (PyCFunction)__pyx_f_6Buffer_insert, METH_VARARGS|METH_KEYWORDS, 0},
  {"append", (PyCFunction)__pyx_f_6Buffer_append, METH_VARARGS|METH_KEYWORDS, 0},
  {"extend", (PyCFunction)__pyx_f_6Buffer_extend, METH_VARARGS|METH_KEYWORDS, 0},
  {0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Buffer = {
  __pyx_f_6Buffer___add__, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  0, /*nb_divide*/
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  0, /*nb_coerce*/
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  0, /*nb_oct*/
  0, /*nb_hex*/
  __pyx_f_6Buffer___iadd__, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  0, /*nb_inplace_divide*/
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
};

static PySequenceMethods __pyx_tp_as_sequence_Buffer = {
  __pyx_f_6Buffer___len__, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  __pyx_sq_item_Buffer, /*sq_item*/
  __pyx_f_6Buffer___getslice__, /*sq_slice*/
  0, /*sq_ass_item*/
  __pyx_sq_ass_slice_Buffer, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Buffer = {
  __pyx_f_6Buffer___len__, /*mp_length*/
  __pyx_f_6Buffer___getitem__, /*mp_subscript*/
  __pyx_mp_ass_subscript_Buffer, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Buffer = {
  __pyx_f_6Buffer___getreadbuffer__, /*bf_getreadbuffer*/
  __pyx_f_6Buffer___getwritebuffer__, /*bf_getwritebuffer*/
  __pyx_f_6Buffer___getsegcount__, /*bf_getsegcount*/
  __pyx_f_6Buffer___getcharbuffer__, /*bf_getcharbuffer*/
};

statichere PyTypeObject __pyx_type_Buffer = {
  PyObject_HEAD_INIT(0)
  0, /*ob_size*/
  "buffer_gap.Buffer", /*tp_name*/
  sizeof(struct __pyx_obj_Buffer), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_Buffer, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  __pyx_f_6Buffer___cmp__, /*tp_compare*/
  __pyx_f_6Buffer___repr__, /*tp_repr*/
  &__pyx_tp_as_number_Buffer, /*tp_as_number*/
  &__pyx_tp_as_sequence_Buffer, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Buffer, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  __pyx_f_6Buffer___str__, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Buffer, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE, /*tp_flags*/
  0, /*tp_doc*/
  __pyx_tp_traverse_Buffer, /*tp_traverse*/
  __pyx_tp_clear_Buffer, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_Buffer, /*tp_methods*/
  0, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  __pyx_f_6Buffer___init__, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_Buffer, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static char (__pyx_k1[]) = "";
static char (__pyx_k4[]) = "";

DL_EXPORT(void) initbuffer_gap(void); /*proto*/
DL_EXPORT(void) initbuffer_gap(void) {
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;
  __pyx_m = Py_InitModule4("buffer_gap", __pyx_methods, __pyx_mdoc, 0, PYTHON_API_VERSION);
  __pyx_b = PyImport_AddModule("__builtin__");
  PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b);
  __pyx_type_Buffer.tp_free = _PyObject_Del;
  if (PyType_Ready(&__pyx_type_Buffer) < 0) {__pyx_filename = __pyx_f1; __pyx_lineno = 16; goto __pyx_L1;}
  if (PyObject_SetAttrString(__pyx_m, "Buffer", (PyObject *)&__pyx_type_Buffer) < 0) {__pyx_filename = __pyx_f1; __pyx_lineno = 16; goto __pyx_L1;}

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":3 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":12 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":16 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":19 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":30 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":42 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":62 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":83 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":85 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":86 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":88 */
  __pyx_1 = PyString_FromString(__pyx_k1); if (!__pyx_1) {__pyx_filename = __pyx_f1; __pyx_lineno = 88; goto __pyx_L1;}
  __pyx_k2 = __pyx_1;
  __pyx_1 = 0;
  __pyx_k3 = 512;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":96 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":100 */
  __pyx_2 = PyString_FromString(__pyx_k4); if (!__pyx_2) {__pyx_filename = __pyx_f1; __pyx_lineno = 100; goto __pyx_L1;}
  __pyx_k5 = __pyx_2;
  __pyx_2 = 0;
  __pyx_k6 = 512;

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":103 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":106 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":109 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":112 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":116 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":120 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":124 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":141 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":145 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":165 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":191 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":206 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":222 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":227 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":247 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":251 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":261 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":271 */

  /* "C:\cygwin\home\pje\PEAK\src/peak/util/buffer_gap.pyx":281 */
  return;
  __pyx_L1:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("buffer_gap");
}

/* Runtime support code */

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(char *funcname) {
  PyObject *py_srcfile = 0;
  PyObject *py_funcname = 0;
  PyObject *py_globals = 0;
  PyObject *empty_tuple = 0;
  PyObject *empty_string = 0;
  PyCodeObject *py_code = 0;
  PyFrameObject *py_frame = 0;
  
  py_srcfile = PyString_FromString(__pyx_filename);
  if (!py_srcfile) goto bad;
  py_funcname = PyString_FromString(funcname);
  if (!py_funcname) goto bad;
  py_globals = PyModule_GetDict(__pyx_m);
  if (!py_globals) goto bad;
  empty_tuple = PyTuple_New(0);
  if (!empty_tuple) goto bad;
  empty_string = PyString_FromString("");
  if (!empty_string) goto bad;
  py_code = PyCode_New(
    0,            /*int argcount,*/
    0,            /*int nlocals,*/
    0,            /*int stacksize,*/
    0,            /*int flags,*/
    empty_string, /*PyObject *code,*/
    empty_tuple,  /*PyObject *consts,*/
    empty_tuple,  /*PyObject *names,*/
    empty_tuple,  /*PyObject *varnames,*/
    empty_tuple,  /*PyObject *freevars,*/
    empty_tuple,  /*PyObject *cellvars,*/
    py_srcfile,   /*PyObject *filename,*/
    py_funcname,  /*PyObject *name,*/
    __pyx_lineno,   /*int firstlineno,*/
    empty_string  /*PyObject *lnotab*/
  );
  if (!py_code) goto bad;
  py_frame = PyFrame_New(
    PyThreadState_Get(), /*PyThreadState *tstate,*/
    py_code,             /*PyCodeObject *code,*/
    py_globals,          /*PyObject *globals,*/
    0                    /*PyObject *locals*/
  );
  if (!py_frame) goto bad;
  py_frame->f_lineno = __pyx_lineno;
  PyTraceBack_Here(py_frame);
bad:
  Py_XDECREF(py_srcfile);
  Py_XDECREF(py_funcname);
  Py_XDECREF(empty_tuple);
  Py_XDECREF(empty_string);
  Py_XDECREF(py_code);
  Py_XDECREF(py_frame);
}

static PyObject *__Pyx_GetName(PyObject *dict, char *name) {
  PyObject *result;
  result = PyObject_GetAttrString(dict, name);
  if (!result)
    PyErr_SetString(PyExc_NameError, name);
  return result;
}

static void __Pyx_Raise(PyObject *type, PyObject *value, PyObject *tb) {
  Py_XINCREF(type);
  Py_XINCREF(value);
  Py_XINCREF(tb);
  /* First, check the traceback argument, replacing None with NULL. */
  if (tb == Py_None) {
    Py_DECREF(tb);
    tb = 0;
  }
  else if (tb != NULL && !PyTraceBack_Check(tb)) {
    PyErr_SetString(PyExc_TypeError,
      "raise: arg 3 must be a traceback or None");
    goto raise_error;
  }
  /* Next, replace a missing value with None */
  if (value == NULL) {
    value = Py_None;
    Py_INCREF(value);
  }
  /* Next, repeatedly, replace a tuple exception with its first item */
  while (PyTuple_Check(type) && PyTuple_Size(type) > 0) {
    PyObject *tmp = type;
    type = PyTuple_GET_ITEM(type, 0);
    Py_INCREF(type);
    Py_DECREF(tmp);
  }
  if (PyString_Check(type))
    ;
  else if (PyClass_Check(type))
    ; /*PyErr_NormalizeException(&type, &value, &tb);*/
  else if (PyInstance_Check(type)) {
    /* Raising an instance.  The value should be a dummy. */
    if (value != Py_None) {
      PyErr_SetString(PyExc_TypeError,
        "instance exception may not have a separate value");
      goto raise_error;
    }
    else {
      /* Normalize to raise <class>, <instance> */
      Py_DECREF(value);
      value = type;
      type = (PyObject*) ((PyInstanceObject*)type)->in_class;
      Py_INCREF(type);
    }
  }
  else {
    /* Not something you can raise.  You get an exception
       anyway, just not what you specified :-) */
    PyErr_Format(PyExc_TypeError,
           "exceptions must be strings, classes, or "
           "instances, not %s", type->ob_type->tp_name);
    goto raise_error;
  }
  PyErr_Restore(type, value, tb);
  return;
raise_error:
  Py_XDECREF(value);
  Py_XDECREF(type);
  Py_XDECREF(tb);
  return;
}

static void __Pyx_WriteUnraisable(char *name) {
  PyObject *old_exc, *old_val, *old_tb;
  PyObject *ctx;
  PyErr_Fetch(&old_exc, &old_val, &old_tb);
  ctx = PyString_FromString(name);
  PyErr_Restore(old_exc, old_val, old_tb);
  if (!ctx)
    ctx = Py_None;
  PyErr_WriteUnraisable(ctx);
}
